name: Deploy static content to Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set timezone to Asia/Taipei
              uses: szenius/set-timezone@v1.2
              with:
                  timezoneLinux: "Asia/Taipei"
                  timezoneMacos: "Asia/Taipei"

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build frontend
              run: pnpm build

            - name: Deploy into 2026/build branch
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  # clone target repo
                  git clone --depth=1 --branch=build "https://x-access-token:${{ secrets.DEPLOY_KEY_2026 }}@github.com/sitcon-tw/2026.git" deploy

                  cd deploy
                  rm -rf _next 404 data stats
                  cp -r ../out/* ./

                  git add .
                  git commit -m "Deploy home site" || echo "No changes to commit"
                  git push origin build
